# Generated by Django 5.0.4 on 2024-04-16 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_tag", "0003_alter_menu_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="menu_tag.menu",
                verbose_name="children",
            ),
        ),
    ]
